role:
  user: user
  admin: admin
  ws_admin: ws_admin
each_index: 1
maximum:
  workspace:
    name: 100
    description: 100
workspace_column: 2
workspace_row: 2
perpage_workspace: 10
pagination:
  per_page: 10
  size: 10
